// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhYZiVjPtXOKA6OeEIwQw6EvvD8MLmzWk',
    appId: '1:972004731215:web:eaaf4dc14ece1500633d3a',
    messagingSenderId: '972004731215',
    projectId: 'romino-25d2f',
    authDomain: 'romino-25d2f.firebaseapp.com',
    storageBucket: 'romino-25d2f.firebasestorage.app',
    measurementId: 'G-PNBRJ0BHFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXTLS7yt7Zgg3_aGor2dLe_aGcLpUW01w',
    appId: '1:972004731215:android:6014ac0ea75f5afe633d3a',
    messagingSenderId: '972004731215',
    projectId: 'romino-25d2f',
    storageBucket: 'romino-25d2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAahbeSUz4KRBsgRtWs5uZH-rJkKX14N0A',
    appId: '1:972004731215:ios:44f026f0ba3b3e4a633d3a',
    messagingSenderId: '972004731215',
    projectId: 'romino-25d2f',
    storageBucket: 'romino-25d2f.firebasestorage.app',
    iosClientId: '972004731215-gookq1c9iliulfj5to9892val8nd5pbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.getin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAahbeSUz4KRBsgRtWs5uZH-rJkKX14N0A',
    appId: '1:972004731215:ios:44f026f0ba3b3e4a633d3a',
    messagingSenderId: '972004731215',
    projectId: 'romino-25d2f',
    storageBucket: 'romino-25d2f.firebasestorage.app',
    iosClientId: '972004731215-gookq1c9iliulfj5to9892val8nd5pbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.getin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhYZiVjPtXOKA6OeEIwQw6EvvD8MLmzWk',
    appId: '1:972004731215:web:690430397b4c22eb633d3a',
    messagingSenderId: '972004731215',
    projectId: 'romino-25d2f',
    authDomain: 'romino-25d2f.firebaseapp.com',
    storageBucket: 'romino-25d2f.firebasestorage.app',
    measurementId: 'G-XK2H16ZYF5',
  );
}
